### ISSUE TITLE
operator can steal utxo

### ISSUE THREAD

**Issue by pthomalla** [omisego/plasma-contracts#102]
## Issue Type 

```
[*] bug report
[ ] feature request
```

## Current Behavior

Operator can steal all the funds in root chain account.

## Steps to Reproduce

![thomalla_heist](https://user-images.githubusercontent.com/247162/58247691-c56f4880-7d49-11e9-8e42-b980638c4f57.png)

1. Operator creates a block that includes `tx1` and `tx2` double-spending shared input `a` and withholds it.
2. Next, she creates IFEs from transactions `tx1` and `tx2`.
3. During period 1 other players will challenge canonicity of tx1 with tx2 and vice versa.
4. Operator waits for period 2, and responds to both challenges by providing inclusion proofs.

This creates double-spend where both transactions are canonical (exiting from outputs `b` and `c`) and are exiting with high priority - priority of input `a`. Since operator chooses the moment when he creates IFEs, he exits first, potentially stealing all the funds from the chain.

Why external observers can't do anything about it? Because challenges are forbidden in period 2. Otherwise they could take revealed merkle proof for transaction `tx1` and show that it precedes `tx2`, making `tx2` non-canonical. 

## Suggested Fix

Challenge should be possible in both periods 1 and 2. Response - only in period 1.

**Comment by boolafish** [comment]
Hmmm isn’t this covered by mass exit basically? Whenever double spend is mined the result should be mass exit isn’t it?

**Comment by paulperegud** [comment]
> Hmmm isn’t this covered by mass exit basically? Whenever double spend is mined the result should be mass exit isn’t it?

No. This is a case of canonical double-spend exiting with high priority - the priority of old input. The priority queue will not help since operator's exit will be the one of the highest priority.

To fix this we need following changes in the contract:
1. canonicity challenge is possible during both first and second periods
2. canonicity response is possible only in first period

And following changes in recommended behavior:
1. when doing IFE provide merkle proof ASAP if you are not the only signer of inputs
2. when challenging canonicity, consider calldata of provided merkle proofs as a proving material for challenges

**Comment by pdobacz** [comment]
:fire: Great find @pthomalla!!

@paulperegud @pthomalla can you guys post the diagram and a precise description of the attack in the issue? The one you just talked me through.

**Comment by paulperegud** [comment]
@pdobacz Done. Updated the original description.

**Comment by boolafish** [comment]
> 2. canonicity response is possible only in first period

Is this okay? I might be able to hold my challenge and not giving you enough time to respond?

**Comment by paulperegud** [comment]
> > 1. canonicity response is possible only in first period
> 
> Is this okay? I might be able to hold my challenge and not giving you enough time to respond?

The answer is here:

> And following changes in recommended behavior:
>
>   1.  when doing IFE provide merkle proof ASAP if you are not the only signer of inputs

We are currently checking if this solution holds water.

**Comment by kfichter** [comment]
Hmmm. You should be able to solve this by marking the inputs to the IFE as "spent" once the IFE finalizes and checking for each finalization of an IFE that all inputs are not spent.

**Comment by boolafish** [comment]
I have a proposal that is more or less similar idea with @paulperegud 's but differs in the flow:

1. Instead of `IFE provide merkle proof ASAP`, while IFE starts, it **has to** decide the "position" of the transaction (If there is inclusion proof to the block, should provide while starting exit. If not provided, the position of such transaction **cannot** change afterward) 
1. A transaction can start as many IFE as it wants. Also, it can be with inclusion proof or not. If not with inclusion proof, any competing tx with inclusion proof would have higher priority and make it non-canonical. If both got inclusion proof, simply compare the TX_POS.
1. Have mechanism to make sure all "output" can only exits/finalized once. Once an input exits, the "exit" itself can join the non-canonical game with highest priority and make IFE with such input non-canonical. We need to make sure output can only exit once because we can start IFE as many times as we want and it might pass the game. Just during processExit nothing would happen.
1. This remove the need of respond stage. Instead of respond, you start a new IFE.

If this works (btw, I am not sure about this XDD):
Pros:
1. Remove respond stage

Cons:
1. Previously, if an user gets the merkle proof of his/her in-flight tx later, he/she can respond without extra cost and get the challenge bond. However, practically speaking, I don't really know why and how would this in happens? Because user would start IFE without inclusion proof only when distrust with operator and operator is withholding data. And how much the chance would the operator later provide the proof data?

**Comment by paulperegud** [comment]
> Hmmm. You should be able to solve this by marking the inputs to the IFE as "spent" once the IFE finalizes and checking for each finalization of an IFE that all inputs are not spent. First IFE would finalize correctly and second would fail the above check & be skipped.

This one works. 

We've spent Friday brainstorming the version where `input->oldest_spender` mapping is being checked on `respond`. Now I see that it has a problem with following sequence of events:
1) `tx1` and `tx1` are challenged
2) operator canonizes `tx1` (the older of two)
3) `tx1` is finalized and removed from the queue via `processExit`, contract GCs the mapping.
4) `tx2` is canonized by the operator
5a) `tx2` is challenged by honest observers
5b) `tx2` is finalized and removed from the queue via `processExit`

`5a` and `5b` can be arranged in such a way that there is a race and execution order is unpredictable. Not good enough.

**Comment by paulperegud** [comment]
To implementer - please remember to update Alice-Bob scenarios in morevp.md in elixir-omg repo.

**Comment by boolafish** [comment]
In the PR of processIFE: https://github.com/omisego/plasma-contracts/pull/256, I implement this idea by:
1. flag all inputs (of same token) processed when the IFE is processed.
1. flag all *piggybacked* outputs (of same token) when the IFE is processed.

Question, is it correct to flag the piggybacked output only?

**Comment by pdobacz** [comment]
> Question, is it correct to flag the piggybacked output only?

I think it is necessary to do so, since if there's no piggyback on the output, the output should be standard exitable by the owner, at their discretion

**Comment by boolafish** [comment]
close as ALD contract has the implementation solving this.
