### ISSUE TITLE
truffle deploy

### ISSUE THREAD

**Issue by InoMurko** [omisego/plasma-contracts#199]
## Issue Type 

```
[ x] bug report
[ ] feature request
```

## Current Behavior
I checked out commit f1493aec965bf3072920bc8cf1b281782c148560
https://github.com/omisego/plasma-contracts/commit/f1493aec965bf3072920bc8cf1b281782c148560

This is the PR merge that introduces Truffle deploy support.

## Steps to Reproduce
1. I start geth with
```
geth --targetgaslimit "6200000" --dev --dev.period 1 --rpc --rpcapi personal,web3,eth,net --rpcaddr 0.0.0.0 --rpcvhosts=* --rpcport=8545 --ws --wsaddr 0.0.0.0 --wsorigins='*'
```
and create the env context with 

```
defmodule ServeThis.Deploy do
  @passphrase "ThisIsATestnetPassphrase"
  @one_hundred_eth trunc(:math.pow(10, 18) * 100)
  @about_4_blocks_time 60_000

  def do_it do

    opts = []
    {:ok, authority} = create_and_fund_authority_addr(opts)
    {:ok, deployer_addr} = get_deployer_address(opts)
    IO.puts authority
    IO.puts deployer_addr
    File.open!(".env", [:write], fn file ->
      IO.puts(file, "DEPLOYER_ADDRESS=#{deployer_addr}")
      IO.puts(file, "DEPLOYER_PASSPHRASE=\"\"")
      IO.puts(file, "AUTHORITY_ADDRESS=#{authority}")
      IO.puts(file, "AUTHORITY_PASSPHRASE=#{@passphrase}")
      host = System.get_env("ETH_CLIENT_HOST") || "localhost"
      IO.puts(file, "ETH_CLIENT_HOST=#{host}")
      port = System.get_env("ETH_CLIENT_PORT") || 8545
      IO.puts(file, "ETH_CLIENT_PORT=#{port}")
      IO.puts(file, "MIN_EXIT_PERIOD=600")
    end)
  end

  def create_and_fund_authority_addr(opts) do
    with {:ok, authority} <- Ethereumex.HttpClient.request("personal_newAccount", [@passphrase], [url: get_host_from_env()]),
         {:ok, _} <- fund_address_from_faucet(authority, opts) do
      {:ok, authority}
    end
  end

  defp get_deployer_address(opts) do
    with {:ok, [addr | _]} <- Ethereumex.HttpClient.eth_accounts([url: get_host_from_env()]),
         do: {:ok, Keyword.get(opts, :faucet, addr)}
  end

  def fund_address_from_faucet(account_enc, opts) do
    {:ok, [default_faucet | _]} = Ethereumex.HttpClient.eth_accounts([url: get_host_from_env()])
    defaults = [faucet: default_faucet, initial_funds: @one_hundred_eth]

    %{faucet: faucet, initial_funds: initial_funds} =
      defaults
      |> Keyword.merge(opts)
      |> Enum.into(%{})

    unlock_if_possible(account_enc)

    params = %{from: faucet, to: account_enc, value: to_hex(initial_funds)}
    {:ok, tx_fund} = send_transaction(params)

    eth_receipt(tx_fund, @about_4_blocks_time)
  end

  def eth_receipt(txhash, timeout \\ 15_000) do
    f = fn ->
      txhash
      |> to_hex()
      |> Ethereumex.HttpClient.eth_get_transaction_receipt([url: get_host_from_env()])
      |> case do
        {:ok, receipt} when receipt != nil -> {:ok, receipt}
        _ -> :repeat
      end
    end

    fn -> repeat_until_ok(f) end
    |> Task.async()
    |> Task.await(timeout)
  end

  def repeat_until_ok(f) do
    Process.sleep(100)

    try do
      case f.() do
        {:ok, _} = return -> return
        _ -> repeat_until_ok(f)
      end
    catch
      _something -> repeat_until_ok(f)
      :error, {:badmatch, _} = _error -> repeat_until_ok(f)
    end
  end

  def send_transaction(txmap) do
    {:ok, receipt_enc} = Ethereumex.HttpClient.eth_send_transaction(txmap, [url: get_host_from_env()])
    {:ok, from_hex(receipt_enc)}
  end

  def to_hex(non_hex)
  def to_hex(raw) when is_binary(raw), do: "0x" <> Base.encode16(raw, case: :lower)
  def to_hex(int) when is_integer(int), do: "0x" <> Integer.to_string(int, 16)

  def from_hex("0x" <> encoded), do: Base.decode16!(encoded, case: :lower)

  defp unlock_if_possible(account_enc) do
    unlock_if_possible(account_enc, :geth)
  end

  defp unlock_if_possible(account_enc, :geth) do
    {:ok, true} = Ethereumex.HttpClient.request("personal_unlockAccount", [account_enc, @passphrase, 0], [url: get_host_from_env()])
  end

  defp unlock_if_possible(_account_enc, :parity) do
    :dont_bother_will_use_personal_sendTransaction
  end

  defp get_host_from_env() do
    host = System.get_env("ETH_CLIENT_HOST") || "localhost"
    port = System.get_env("ETH_CLIENT_PORT") || 8545
    "http://#{host}:#{port}"
  end
end

```

this creates something like
```
DEPLOYER_ADDRESS=0xc2d2be1c1f7b5af68859a6053afc8bcadb472a15
DEPLOYER_PASSPHRASE=""
AUTHORITY_ADDRESS=0xe9f922b07765c1683cdc6774c7ed8d1c54ef1b23
AUTHORITY_PASSPHRASE=ThisIsATestnetPassphrase
ETH_CLIENT_HOST=localhost
ETH_CLIENT_PORT=8545
MIN_EXIT_PERIOD=600
```

After this part I run:
```
plasma-contracts  (HEAD detached at f1493ae) $ npx truffle migrate --network local

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


Starting migrations...
======================
> Network name:    'local'
> Network id:      1337
> Block gas limit: 0x5e9ac0


1_check_authority_address.js
============================

   ⠋ Saving migration to chain.Error: Error: Error: Returned error: exceeds block gas limit
    at Object.run (/opt/elixir-omg/plasma-contracts/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.21 (core: 5.0.21)
Node v10.15.2
plasma-contracts  (HEAD detached at f1493ae) $ 
```

Which doesn't work as expected. Checking out *master* and it works, now I wonder what was fixed and whether we could apply the fix to these contracts?
## System Specs
OSx

npx --version
5.8.0

**Comment by InoMurko** [comment]
Reference https://github.com/omisego/elixir-omg/pull/875

cc @kevsul

**Comment by boolafish** [comment]
#### Root cause
Haha, this is an interesting one. After tracing this, it seems like there is a mismatch from truffle's doc and their implementation. I put an issue for this: https://github.com/trufflesuite/truffle/issues/2278. So this happens because it try to send transaction with a gas of 6721975 which exceeds your local blockchain gas limit.

However, on the other hand, do we need to put our blockchain gas limit to 620000? I guess we can move to 7000000 as I checked the rinkenby (our test env) seems to be around that: https://www.rinkeby.io/#stats

The only low gas limit test-net is ropsten, which is still 4.7m. see: https://github.com/ethereum/ropsten/issues/19

#### potential solution
1. You increase your geth gas limit to 7m.
2. In truffle-config, we add a line of `gas: 6000000`. (or anything larger then 5m, since the `RootChain.sol` need close to 5m to deploy)

Which one do you think it makes more sense to your side and general of our use cases? I feel (1) is applicable as all our using network would have higher gas limit anyway, and keep our config in-sync with default values. But I am opening to hear different voices.

**Comment by pdobacz** [comment]
> do we need to put our blockchain gas limit to 620000? 

not sure if I've got the right context, but I think contract deployment used to snugly fit into those 6.2M gas. The reason we kept the block gas limit close to the actual usage was to pick up any spurious increases of gas usage.

So 7M is probably fine too, as long as we're still in control of this.

**Comment by boolafish** [comment]
I am talking about this setup `geth --targetgaslimit "6200000" ...`.

So the issue is that when truffle runs `deployer.deploy(XXX)`, it would pass in some gas value on that transaction, now default to `6721975` sadly larger than the geth setup. We can add config to decrease that as long as it is larger than around 5m (RootChain.sol deployment cost, which is our real limit on gas). I just feel there is probably no benefit to use 6200000 if every our testnet is using limit around 7m and we can fix this without introducing any more magic config numbers?

**Comment by pdobacz** [comment]
Hm, I think I didn't have the context to put in a sensible comment :sweat_smile:.

You're right, bumping this is not an issue, as long as we know we'll detect sudden increases of gas usage and are able to reason about those. And I think we are detecting that elsewhere, so proposed solution is :+1:

**Comment by InoMurko** [comment]
@boolafish so did the gas limit/requirement in latest master change?
Because deploying master without *any* change works. Was _RootChain_ refactored?

**Comment by boolafish** [comment]
@InoMurko, no the contract itself doesn't change. It is the deployer changed. Now the deployer would by default send `6721975` on the deploy transaction, that's why it breaks. That's the default value from truffle (though wrongly docemented....). As a result, I am wondering do I need to decrease gas value sent while deploy or people are fine to just test with higher gas limit blockchain?

**Comment by InoMurko** [comment]
Let me test this and see what works best!

**Comment by InoMurko** [comment]
@boolafish confirmed 7000000 gas limit on geth solve the issue.

**Comment by boolafish** [comment]
Reopen this as it seems like `geth --targetgaslimit xxx`  would not set the node directly to such limit, but move to there gradually.

This can be reproduced by
```
geth console --targetgaslimit "8000000" --dev --dev.period 1 --rpc --rpcapi personal,web3,eth,net --rpcport=8545
```
and then use
```
eth.getBlock("latest").gasLimit
```
to query the gas limit. You can observe that the limit grows gradually, starting with some 6m value.

To make development easier, probably we should go back to the original approach on limit the deploy gas to 6m in truffle config then.

**Comment by InoMurko** [comment]
FYI, `targetgaslimit` is a deprecated flag.
```
-miner.gastarget '8000000' --miner.gaslimit '8000000'
```
are the alternative flags.

*BUT* because the miner gradually increases the gaslimit these flags don't really matter. Geth succeeds in deploying the third time because it reaches a gaslimit that is sufficient to deploy the contracts. (*Regardless* of gastarget and gaslimit flags!)
