### ISSUE TITLE
IFE with deposit tx can have wrong priority

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#216]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior
Let's say we have the following three blocks, two consecutive child chain block and another deposit block:
[valid_tx] [invalid_tx] [deposit_tx]

Now a user A owns the `valid_tx` while invalid operator owns `invalid_tx` and `deposit_tx`. The child chain block with `invalid_tx` is withhold by the operator however, user A verified the block with `valid_tx` already and decide to do another valid tx and send to operator.

Now, operator do an IFE with `invalid_tx` and `deposit_tx` as input, and the youngest utxoPos would be `deposit_tx`. The problem is that a deposit tx have 1 week higher priority then normal plasma tx. As a result, even user A tries to IFE with the priority of `valid_tx`, it will still lose the priority over the `deposit_tx` that hides the `invalid_tx`.

## Expected Behavior
Should exit with right priority.

## Suggested Fix
hmm, check the "latest exit time" instead of "youngest utxopos" of inputs?

## Motivation for Change
Fix bug

**Comment by kevsul** [comment]
> Now, operator do an IFE with invalid_tx and deposit_tx as input, and the youngest utxoPos would be deposit_tx. The problem is that a deposit tx have 1 week higher priority then normal plasma tx. 

The way I understood it was that a deposit tx only has a higher priority if it is the transaction being exited. The inflight tx in the example has a deposit tx as its youngest input, which affects its ordering in the priority queue, but it shouldn't get the deposit tx priority bonus because of that.

**Comment by pdobacz** [comment]
This is very interesting.

Hmmm, I think second @kevsul here. The youngest part is calculated based on the utxo position and not priority. So the `deposit_tx` will be as old as the sequence indicates, it doesn't get the bonus, c.f. https://github.com/omisego/plasma-contracts/blob/master/contracts/RootChain.sol#L505 and https://github.com/omisego/plasma-contracts/blob/master/contracts/RootChain.sol#L520

However, I think its well worth adding a test (functional, like the "python ones" we have), recreating the scenario and asserting that in fact, priority of the said IFE will be low.

That is to cover a situation when someone would in fact use the "lowest priority input" instead of "youngest input" in the future.

**Comment by boolafish** [comment]
If you trace the code a bit further from the linked code pointer above, the Rootchain.sol would take utxopos and check is that a deposit tx and end up using the priority of deposit tx. We need to fix this as well add test for sure.

**Comment by pdobacz** [comment]
Whoops, I think I've stopped tracing too early :man_facepalming:.

**Comment by boolafish** [comment]
Please make sure this is fixed during the effort of this: https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol#L166-L170
