### ISSUE TITLE
Transparent handling of token standards (ERC20, ERC721, etc)

### ISSUE THREAD

**Issue by paulperegud** [omisego/plasma-contracts#282]
We can handle different token standards transparently - without introducing a specialized exit game or specialized transaction types. **Note - we can do this only now!** Adding such functionality later would not be possible via upgrade mechanism (discussed with @boolafish) since it requires a change in output format.

#### Vaults today
At this moment vaults implement two callbacks (argument list is the proposed one, not the one implemented):
* `withdraw(token_contract_address, owner, standard_specific_data): void` (throw if something is wrong)
* `process_deposit(token_contract_address, owner, standard_specific_data): void` (throw if something has gone wrong)

Logic of choosing what vault is the proper one is tied to transaction type. That means that we have one tx type for ERC20 and one for ERC721 and one for mix of them. We can do better.

#### Required change in vaults
We add one more callback that each vault needs to implement. It looks like this.
isPrintingMoney(this_vault_specific_inputs: [output()], this_vault_specific_outputs: [output()]): boolean

#### Required change in output format
We add one more field and we drop `amount` in favor of `standard_specific_data`. Modified output format looks like this:
* `output_guard` - ....
* `token_standard` <- new field, `uint`
* `token_contract_address` - `address`
* `standard_specific_data` - `bytes`

Last field being just `bytes` hides internal structure of `standard_specific_data`. This is important since Solidity does not support dynamic types and we want to avoid leaking of information about the types and number of elements inside all over the codebase. We take whatever contents of that field and RLP encode them.

All operations on standard_specific_data would be done inside of the 3 callbacks above - callback would be the only one that unpacks that field. Contract would choose proper vault by reading the `token_standard` value. E.g. when `isPrintingMoney` needs to be called, inputs and outputs need to be grouped by `token_standard` value and for each group we call `isPrintingMoney` once.

Example of the way token specific data can be encoded is below.
For ERC721:
* `token_standard` = 2 -> erc721 vault implementation
* `standard_specific_data` = `RLP.encode([uint256 token_uid, ...]): bytes`

For ERC20:
* `token_standard` = 1 -> 
* `standard_specific_data` = `RLP.encode(uint256 amount): bytes`

For buggy ERC20 implementation:
* `token_standard` = x -> 
* `standard_specific_data` = `RLP.encode(uint256 amount): bytes`).

**Comment by boolafish** [comment]
yeah, I think this is the real `WireTransaction` data structure that can survive foreseeable future.

one question, what does `process_deposit` do? Does it generates the transaction automatically and submit it to block?

btw, how's your talk with @pdobacz on this?

**Comment by paulperegud** [comment]
Process_deposit in case of ERC20 does `token_address.transferFrom(msg.sender, address(this), amount)` - just as `depositFrom(...)` from RootChain.sol does that.

**Comment by paulperegud** [comment]
This one is also true for events generated by vaults. We track multiple contracts for deposit and withdrawal events, but events themselves can follow similar pattern. EVM allows for `bytes` data to be included in events and we can place `standard_specific_data` there.

**Comment by pgebal** [comment]
We can think of `token_standard` as a vault id, it's an int that maps to a specific vault address.

I like that solution. @boolafish if you like @paulperegud 's idea I can start working on that.

**Comment by boolafish** [comment]
I like it. Can you comment an estimation of time to do this first and then go into implementation? The main concern of me is whether elixir is happy taking more changes and the audit timeline that is two weeks after XDD

**Comment by pdobacz** [comment]
I looked into this and didn't think that it would cause (huge) breakage in the (current) `elixir-omg` implementation, but I might be wrong.

1. How this would (if at all) the public APIs/protocol?
2. Is it only the interface of the `Deposit` events, which will now contain the packed data for amount in `amount_data`?
3. Can the change to the interface of the `Deposit` events be done via a later upgrade?

**Comment by boolafish** [comment]
hmm interesting but nice to hear that the effort on elixir might not be large.
Curious though, both this and #290 requires the rlp encode trick and that's why I kind of feel might need more effort on elixir side but you seems to feel differently on the load between two issues? What part am I missing here?

**Comment by pdobacz** [comment]
> requires the rlp encode trick and that's why I kind of feel might need more effort on elixir side but you seems to feel differently on the load between two issues?

hm, I think, on `elixir-omg` side the RLP encode trick is never too much of an issue. We just RLP decode and pass typed data around in both cases. In terms of the effort of the RLP trick I was only concerned about `.sol` side.

**Comment by paulperegud** [comment]
> How this would (if at all) the public APIs/protocol?

Changes caused by vaults themselves, not this proposal:
* Currency is now a pair {vault_id, token_address}. This should be taken into account for every function that accepts currency as a parameter. E.g. `addToken` or `processExits`. Same is true for the events about deposits or withdrawals (aka exit finalization).

Changes caused by this proposal. We can have only one of two:
* generic events about Deposit and Withdrawal with cryptic `standard_specific_data` field
* **or** ERC standard specific events that require an additional bit of code per vault type on client side. On positive side - they will be 'human readable'.

Please note that tokens themselves also generate events about token movement. Can we possibly utilize those? (strong assumption: implementation follow the standard)

> Is it only the interface of the Deposit events, which will now contain the packed data for amount in amount_data?

Yes, as `bytes`. Or alternative described above with custom event type per vault.

> Can the change to the interface of the Deposit events be done via a later upgrade?

The road to do that would be - to add new vault. Vaults being forbidden from mixing funds, means that we will have two parallel flavors of every token. One on the old interface, one on the new interface. Former possibly _**being cheaper**_.

**Comment by boolafish** [comment]
> Currency is now a pair {vault_id, token_address}. This should be taken into account for every function that accepts currency as a parameter.

Yeah, this is something I'd like to also note. To enable upgrade by deploying new vault, each vault might need to have its own priority queue to isolate from other vaults?

Or, alternatively, we make vault wait the same period as ExitGame, and people just must exit before any rogue vault.

**Comment by boolafish** [comment]
During the call with @paulperegud @pdobacz and @kevsul , here is our decision of progressing this:

1. Don't apply the output structure change now since the main benefit compare to what we have now is for ERC721 which the path toward there is not fully clear, plus we might be paying more by adding extra abstraction now instead of getting the benefit.
1. If we have time (optionally), change the exit queue to be per `(vault_id, token_address)` pair, aka `queue_id`. Reason for this is that this would support future upgrade to this tx structure design and also allow us to upgrade via a new vault for same ERC protocol now. (Current design does not support full upgrade of a, eg. ERC20 vault. Then we can adjust to changes like: #312 )

**Comment by boolafish** [comment]
btw, it was @piotr’s idea of `queueId` which it is not until recently that I think I understand a bit more on what he’s trying to propose.

I just realize if we change `addToken(token)` to sth like `addExitQueue(queueId)`, and during enqueue, instead of asking for `(vaultId, token)` pair, we just provide the `queueId`, the framework is more flexible to changes in the future. If we somehow find another possible reason/stuff that needs extra isolation aside from `vaultId, token` pair (for instance, if a plapp wants its own queue instead?) then this would leave us in a better place.

Downside of course is....more breaking existing interfaces @@

(btw, I hope I get the Piotr's intention right :p )

**Comment by boolafish** [comment]
close as #324 merged
