### ISSUE TITLE
'Out of gas' problem when deploying PaymentExitGame

### ISSUE THREAD

**Issue by kevsul** [omisego/plasma-contracts#287]
Deploying the PaymentExitGame contract raises an 'out of gas' error.
On further investigation, the problem appears to be the size of the bytecode of the contract.
Specifically the size of the inherited PaymentInFlightExitRouter, which has grown significantly lately. 
Although PaymentInFlightExitRouter doesn't do much itself and is mostly a wrapper that calls various controllers, the problem is with the wrapped methods - each one has a large amount of parameters which contribute to the size of the bytecode.

**Comment by boolafish** [comment]
[Note on call with @kevsul ]
#### Short term solution
1. skip e2e test in PR #249 to allow merge.
1. Prioritize #286 and have a PR to turn on optimizer to enable deployment of `PaymentExitGame` again.

#### Long term solution (idea)
Since we are already using `router-controller` pattern and it still get over-sized on `router`. To be honest, I think it is hard to make `router` thinner further. The real scalable solution is really by removing the `router` and lets the client calls each controller directly. Some changes are necessary such as shared storage contract and make controller from lib -> contract. 

Framework part need to be able to register multiple contracts for one tx type.

**Comment by kevsul** [comment]
Closing this as the latest version of solc (0.5.11) optimizes the contract to well under the limit
