### ISSUE TITLE
BlockController - authority should not be allowed to set a new authority

### ISSUE THREAD

**Issue by tintinweb** [omisego/plasma-contracts#403]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior

![image](https://user-images.githubusercontent.com/2865694/67688247-d035a580-f999-11e9-9e0c-ed923c42b12a.png)

https://github.com/omisego/plasma-contracts/blob/ca378932458e2e9156aa00f76298088a12b16fe9/plasma_framework/contracts/src/framework/BlockController.sol#L69-L72

`deployer` initially sets the account that is allowed to submit new blocks as `authority`. `authority` can set a new `authority` at will.  In a system that is set-up and maintained by a `maintainer` role (multi-sig) that can upgrade certain parts of the system it is unexpected for another role to be able to pass along its permissions. The [security specification](https://github.com/omisego/plasma-contracts/blob/422f77adabbcca0061cbf73df2ac12b73ed054f8/security/spec.md) notes that the `authority` role is only used to submit blocks:

> Authority: EOA used exclusively to submit plasma block hashes to the root chain. The child chain assumes at deployment that the authority account has nonce zero and no transactions have been sent from it.

However, **no transactions** might not be possible as `authority` is the only one to `activateChildChain`. Once activated, the child chain cannot be de-activated but `authority` can change.

[elixir-omg#managing-the-operator-address](https://github.com/omisego/elixir-omg#managing-the-operator-address) notes the following for `operator` aka `authority`: 

> As a consequence, the operator address must never send any other transactions, if it intends to continue submitting blocks. (Workarounds to this limitation are available, if there's such requirement.)

Additionally, `setAuthority` should emit an event to allow participants to react to this change in the system and have an audit trial.

## Suggested Fix

* authority should strictly be used for block submission. maintainer should set new `authority` instead.
* emit an event when setting a new authority.

**Comment by boolafish** [comment]
just to clarify things a bit

> However, no transactions might not be possible as authority is the only one to activateChildChain. Once activated, the child chain cannot be de-activated but authority can change.

[elixir-omg#nonces-restriction](https://github.com/omisego/elixir-omg#nonces-restriction) notes the real key point of nonce is to be: 
```
Child block number 1000 uses Ethereum nonce 1, child block number 2000 uses Ethereum nonce 2, always.
```
And that's why we have the function `activateChildChain` actually, to bump the nonce from 0 to 1.
see: https://github.com/omisego/plasma-contracts/issues/304#issuecomment-538285330

So the "no transactions" here should mean no more other transaction aside from `activateChildChain` and `submitBlock` if we want to keep the re-org protection by nonce.

On the other hand, the purpose of `setAuthority` is really to replace the re-org protection mechanism. As a result, once we moved to such mechanism, we don't care about old re-org protection nonce anymore.

here is the proposed new re-org protection mechanism: https://gist.github.com/paulperegud/3fb4bb96693abe2e0b175f7b20e64362. The idea is to change the authority to a smart contract that implements the new re-org protection.

----

Above is some long story of the background, but I agree that it is better to be done with `maintainer` instead + should emit event.

I will also discuss with the team that how strong are we feeling to implement such feature in the future (new re-org protection on elixir-omg side). Removing unnecessary feature (the function) might be an alternative solution to simplify the code.

**Comment by thec00n** [comment]
I think `setAuthority` in its current implementation is inconsistent how we split up the roles between `maintainer` and `authority`. I agree with @tintinweb that if we want to be able to replace the authority address then it should be done by the `maintainer` and with a quarantine time of greater than the min exit period. 

@boolafish Correct me if I understand this wrongly. Adding a more sophisticated reorg protection mechanism is currently just an idea. If we ever decide to do that we need swap the authority address in production and that's in itself a considerable risk. For now I would lean more towards removing `setAuthority` and recognize payments on the child chain with a sufficient safety buffer. Does that make sense?

**Comment by boolafish** [comment]
>  it should be done by the maintainer and with a quarantine time of greater than the min exit period.

There is no need of the quarantined period here as authority being fraud is always being considered and would still be fine(-ish) under plasma M(ore)VP (triggering mass exit).

> If we ever decide to do that we need swap the authority address in production and that's in itself a considerable risk.

well...yes but still this risk might be lower than a hard upgrade, and I believe it is pretty manageable.

>  For now I would lean more towards removing setAuthority 

I have same tendency here though more from the side to not keep code that we might have low change to use. Or we might/will actually just do a hard upgrade so we can sneak new re-org mechanism in at that point.

**Comment by boolafish** [comment]
Solving this by removing the `setAuthority` function in #434
