### ISSUE TITLE
RLPReader - _itemLength() out of bounds access

### ISSUE THREAD

**Issue by tintinweb** [omisego/plasma-contracts#409]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior
The RLPReader library is used to decode bytestreams into RLP-objects vice versa. RLP is a compact tag, length, value format to encode bytes, strings and lists. Lists include RLP objects themselves and should be decoded recursively.

https://github.com/omisego/plasma-contracts/blob/85d2d2c953f32c524eb3ebb3faa7dbc994f02eb5/plasma_framework/contracts/src/utils/RLPReader.sol#L144

`RLPReader._itemLength()` takes a `memPtr` and attempts to decode an RLP encoded item to return its complete size (tag + length + payload). Unfortunately, the method does not have any information about the length of the buffer it is working on. Therefore it effectively cannot check if it reads out-of-bounds and has to rely on the caller to do bounds checking which is not easily possible.

##### Empty Short String `0x80` causes out-of-bounds read

https://github.com/omisego/plasma-contracts/blob/85d2d2c953f32c524eb3ebb3faa7dbc994f02eb5/plasma_framework/contracts/src/utils/RLPReader.sol#L154-L166

* `bytes(0x80).toRlpItem().toList()` calls `_itemLength()`
* `STRING_SHORT_START = 0x80`
* `byte0 = 0x80`
* `itemLen = 0x80-0x80 +1 = 1` // only the tag-byte, there is no data-byte and that's totally valid
* The code proceeds and reads one byte past the buffer (`byte1`)
* no error condition is raised
* correct length is returned

##### Hinting wrong length will consider out-of-bounds bytes for datalength

https://github.com/omisego/plasma-contracts/blob/85d2d2c953f32c524eb3ebb3faa7dbc994f02eb5/plasma_framework/contracts/src/utils/RLPReader.sol#L166-L183

## Suggested Fix

Pass the buffer instead of the memory pointer and perform bounds-checks while decoding.

**Comment by tintinweb** [comment]
That issue was a leftover from our call on monday.

The first issue may already have been addressed with #396.
The 2nd one might still use out of bounds bytes but it should fail in one of the requires early on afterwards. It would still be better to check that enough bytes are available in the buffer before accessing them.

we're not looking any further with the RLPReader right now as it is undergoing some changes.

cheers.

cheers.

**Comment by thec00n** [comment]
@tintinweb The 2nd case is tricky when you process an RLPItem that is a list. You can only really know if the items in the list have a combined length that is greater than the list when you have the sum (https://github.com/omisego/plasma-contracts/blob/b4260aa9318f9e3a231e8d99b9c0223fddb959d3/plasma_framework/contracts/src/utils/RLPReader.sol#L58-L60). That's why I have renamed the function `decodeItemLengthUnsafe` and check the length in every instance after it returns. If you find a way to do this more elegantly let me know. 

I have also added some new test cases, check:

https://github.com/omisego/plasma-contracts/blob/376_rlp_improvements/plasma_framework/test/src/utils/RLPInvalid.test.js

Also I have removed all utility functions from RLPReader that are not used by any of the productions code and move then into the RLPMock class. 


Mythx is reporting integer overflows in a library and I can’t reproduce the overflows. Could you guys look into it?

Report:
https://gist.github.com/thec00n/15ce59c8232c56dcb48be5b85cfff5df
Contract:
https://gist.github.com/thec00n/60813e74d5ff6eef75fe44637546ee41
