### ISSUE TITLE
Potential exit-priority issue for standard exits when a malicious maintainer sets a faulty deposit verifier

### ISSUE THREAD

**Issue by ezulkosk** [omisego/plasma-contracts#412]
## Issue Type 

[x] bug report
[ ] feature request

## Current Behavior

I'm not fully sure if this is an issue or not yet, but I'd like to bring up a scenario in which a malicious maintainer sets a faulty deposit verifier, and how it may be problematic for standard exits. This relates to the `Vault.setDepositVerifier()` function (specifically the maturity timestamp on L52), as well as the fact that exits of deposits are shorter than normal (as defined in `ExitableTimestamp.sol`). Below, we assume that the maintainer and operator are colluding (or are the same address), and we generally refer to these authorities as "the maintainer".

**Scenario**: _A malicious maintainer steals funds by setting a bad deposit verifier_
1. At time `T_0`, the maintainer sees a very large payment of `N` tokens from Alice to Bob, which is still in-flight. At this moment, the maintainer first sets a new deposit verifier, which will allow the maintainer to verify any deposit they want. This will only go into effect after the delay as specified on `Vault.sol#L52` (i.e., after 1 exit period). Shortly after, the in-flight transaction is included in the child chain, say at time `T_0 + delta`.
2. At some point soon after, Bob realizes that this new deposit verifier is fraudulent. Since Bob sees the transaction included in the child chain, he attempts a standard exit on the transaction. This exit will be allowed to complete at time `T_0 + delta + 2 exit periods`. 
3. At time `T_0 + 1 exit period`, the malicious maintainer creates a fake deposit indicating that they've deposited `N` tokens, where `N` is the amount in the payment above. This will be scheduled for exit at time `T_0 + 2 exit periods`.
4. The malicious maintainer exits at time `T_0 + 2 exit periods`.
5. Bob cannot exit at time `T_0 + delta + 2 exit periods`, since in step (4) all the funds were wiped.

Is the above interpretation correct (in particular, are the priorities of the exits, as described in steps 2 and 3, correct)? 

Further, if in step 2 Bob created an in-flight exit, I believe Bob would be able to exit with his funds, since the transaction's priority would be associated with the youngest-input "moreVP-style", as opposed to the "MVP-style" priority. Is this also accurate?

## Expected Behavior

Since in step 2 Bob sees that the transaction has been included in the child chain, he may be inclined to perform a standard exit (and should be able to?). However, assuming the above interpretation is correct, he may be required to start an in-flight exit in order to not lose funds.

## Suggested Fix
Users should be made aware of scenarios where standard exits are insufficient. Alternatively, consider a longer delay before the new deposit verifier goes into effect.

**Comment by boolafish** [comment]
> Further, if in step 2 Bob created an in-flight exit, I believe Bob would be able to exit with his funds, since the transaction's priority would be associated with the youngest-input "moreVP-style", as opposed to the "MVP-style" priority. Is this also accurate?

Yes, this is correct. And because of this, I chose a smaller timeframe for vault related update as this is the minimum requirement that keeps same assumption as original Plasma MVP.

> Users should be made aware of scenarios where standard exits are insufficient. 

Hmmm, yeah. I guess this might be part of watcher's (or some UI display's) job when seeing new deposit verifier. They should tell what are the steps to be done if you don't trust the new contract.

> Alternatively, consider a longer delay before the new deposit verifier goes into effect.

Arguably, you can do the exact same thing above just the `delta` would be from 1 week to 3 weeks. I think user would already consider data withholding for close to a week should in-flight exit to safe guard his/her fund already.

**Comment by boolafish** [comment]
> However, with the current setup I think the delta could actually be very small (e.g., 15 minutes) and still be problematic

I re-read the description and just realize this is a scenario that wasn't considered previously. My previous comment did not grab all the detail in description, sorry for that. I always thought in the case of vault it would only need IFE after an invalid transaction mined, just that can happened anytime after quarantined period passed. Now it shows that user need to IFE once an invalid registration happens too.

I think I would agree to extend the period to 2 weeks so that the expected default user action would be the same as a bad exit game is registered, start SE within a week of bad registration from maintainer. 

cc. @pdobacz @paulperegud for second eyes on protocol layer design.

**Comment by pdobacz** [comment]
> I think I would agree to extend the period to 2 weeks so that the expected default user action would be the same as a bad exit game is registered, start SE within a week of bad registration from maintainer.

seems good :+1:.

I also have a thought that IFE's should not be ever bloated, where the protocol would require users to IFE (as opposed to SE) on any occasions other than txs being in-flight and jeopardized. Our security assumptions is that there's going to be _few_ IFEs trying to get out, in an event of a mass exit. _Few_ is order-of-magnitude of a single block. ~1 week worth of blocks of IFEs would be too much to safely start on time.

So I'd say, as a rule of thumb, any other exit-triggering events like bad vaults/verifiers/exit games must always look towards SEs as their safety valves, never IFEs.
