### ISSUE TITLE
Merkle - The implementation does not enforce inclusion of leaf nodes.

### ISSUE THREAD

**Issue by cleanunicorn** [omisego/plasma-contracts#425]
## Issue Type 

- [x] bug report

## Current Behavior
A observation with the current Merkle tree implementation is that not necessarily leaf nodes can be validated. One can call `checkMembership()` and instead of providing a leaf, it can provide a hash within the Merkle tree.

https://github.com/omisego/plasma-contracts/blob/ca378932458e2e9156aa00f76298088a12b16fe9/plasma_framework/contracts/src/utils/Merkle.sol#L9-L42

The current implementation will validate the provided "leaf" and return `true`. This is a known problem of Merkle trees https://en.wikipedia.org/wiki/Merkle_tree#Second_preimage_attack. 

## Expected Behavior
It should only validate leaf nodes as being included in the Merkle tree.

## Steps to Reproduce
Provide a hash from within the Merkle tree as the `leaf` argument, the index has to match the index of that node in regards to its current level in the tree. 
The `rootHash` has to be the correct Merkle tree `rootHash`.
The proof has to skip the necessary number of levels because the nodes "underneath" the provided "leaf" will not be processed.

## Suggested Fix
A remediation needs a fixed Merkle tree size which you have, but it also needs a prepended byte to each node in the tree. Another way would be to create a structure for the Merkle node and mark it as `leaf` or `no leaf`.

## Motivation for Change
If this change is made, the method will only validate provided leafs.

**Comment by pgebal** [comment]
I think that's not an issue in our use case. We use MT lib to prove that transaction is included in a block stored in plasma.`leaf` argument is always calculated in our plasma contracts as a hash of a transaction bytes provided by a user. To make false claims about transaction being included in a block, user would need to prepare a transaction that is a preimage of a node. That looks to me as breaking the hash function. @boolafish @cleanunicorn

**Comment by paulperegud** [comment]
There might be some vectors that would allow attacked to exploit the library. Attacker would need to provide a 32 bytes long value that is at the same time a hash of node in the tree AND a valid transaction (both valid RLP encoded tx and satisfies additional checks). Alternatively attacker would need to find an execution path where we don't unpack the transaction. Are we sure that there are no such paths?

We can patch the contract and fix tree depth. Alternatively, to still have the ability to have a tree of variable depth, we can do:
1) hash tx body with salt (any value) 
2) pass the Tx body into the library itself, instead of doing the hashing/salting outside

Appropriate changes in client software are also needed.

**Comment by pgebal** [comment]
OK. I got it now.

**Comment by paulperegud** [comment]
Vectors of exploitation that are impossible are making a fake standard exit or IFE exit. Reason - attacker would have to discover a node which pre-image (apart of other conditions) satisfies a property of having a `owner` field with value representing Ethereum address for which they have a private key. Even with lax spending condition that would somehow enable skipping the signature check, attacker would exit with randomly addressed non-existant token.

**Comment by pgebal** [comment]
All PRs merged. Done.
