### ISSUE TITLE
Process exit would not return bond if the exit is omitted

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#440]
## Issue Type 

```
[x] discussion
```

## Current Behavior
Currently, both process SE and process IFE would not return bond when the exit is omitted when checked input/output is flagged as spent. The bond would just be locked to the exit game contract.

Another issue was that if user starts IFE without piggyback, the user would lost the bond as startIFE does not enqueue. Thus processExits does not even process this IFE.

## Expected Behavior
Shall we return the bond when:
1. The SE output is already flagged?
1. One of the IFE input is already flagged (+ all piggyback cleared or nothing piggybacked)?

Or shall we consider this as trying to do invalid exit so we don't return bond?

Also, for the IFE without piggyback part, it seems like bond should be returned?

example scenario:
> Just like you freaked out because you didn’t see the transaction in a block so you started an IFE, but then you see it so you just want your bond back but keep the funds on plasma. is this valid?

## Steps to Reproduce
eg. startSE an output, and then startSE again?

## Suggested Fix
N/A

## Motivation for Change
Clarify the protocol and make sure the bond system work as expected.

**Comment by pdobacz** [comment]
If this is fixable, it would be nice if it also provided an IFE-specific event (e.g. menioning the IFETx hash and/or exit_id) that gets emitted the moment a "void" IFE (non-piggybacked or piggybacked but challenged until no valid pb's remain etc.) "finalizes".

This would ease the solution of https://github.com/omisego/elixir-omg/issues/811, since otherwise the watcher would need to check the phase of an IFE to figure out whether it can be forgotten yet or not.

**Comment by boolafish** [comment]
[NOTE]
An alternative idea arise on the ALD sync call.
We could potentially have another call to delete the exit (if nobody piggybacks) and that would get the bond back. The call should probably be after piggyback or even the exit finalization period.
