### ISSUE TITLE
IFE integration docs processExits

### ISSUE THREAD

**Issue by InoMurko** [omisego/plasma-contracts#539]
From the tests in elixir-omg I think doing an IFE needs a processExits call as well, but this information was not available reading integration docs https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/docs/integration-docs/integration-doc.md#processing-a-standard-exit

https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/docs/integration-docs/integration-doc.md

Am I missing something or is this really missing? What is the link between IFE and exit processing?

Cheers

**Comment by boolafish** [comment]
It's missing from the doc. After piggyback, one can processExits for the IFE. 
The process is mostly same as SE, if you want to go ahead now, you can get the IFE exitId from this helper function of ExitGame contract:

https://github.com/omisego/plasma-contracts/blob/6429cb9feff9d90c9559ce30a279d1f0a332924b/plasma_framework/contracts/src/exits/payment/PaymentExitGame.sol#L61

Will leave this issue open until we add the doc.

**Comment by InoMurko** [comment]
you've said
>  one can processExits for the IFE (of that token).

does that mean he doesn't have to? what are the implications if one doesn't call process exit?

also, have we documented what the mechanics of these things are? for example... we know we need to do these things... but would integrators know *why* (purpose)?

**Comment by kevsul** [comment]
You don't have to process your own exits - anyone can process anyone else's exits that are on the queue (i.e. ready to be processed).

Processing an exit just means transferring the money from the vault to the owner.

However, exits have to be processed in order - the exit at the top of the queue _must_ be processed before the 2nd exit on the queue.

Which means that if you're not in a hurry to get your money, instead of spending the gas to process your exit you can just wait and hope that somebody more impatient behind you in the queue will do it for you.

To avoid these kinds of games of chicken, we (the network operator) will probably pay the gas to periodically process exits and empty the queue (at least initially).

**Comment by InoMurko** [comment]
Two questions in reverse order:
First:
> To avoid these kinds of games of chicken, we (the network operator) will probably pay the gas to periodically process exits and empty the queue (at least initially).

Does this part of the system already exist? How are we planning to do this? Are we able to observe and metric the queues?

Second:
IFE first step is that I get my tokens back on OMG network, second step after processing the exit is that I get back on the ethereum network? So... IFE is basically **revert transaction** + standard exit? Sorry, this might be very basic.

**Comment by kevsul** [comment]
> Two questions in reverse order:
> First:
> 
> > To avoid these kinds of games of chicken, we (the network operator) will probably pay the gas to periodically process exits and empty the queue (at least initially).
> 
> Does this part of the system already exist? How are we planning to do this? Are we able to observe and metric the queues?

Observing the queues is pretty easy, but AFAIK whether and how we do this hasn't been set in stone yet.

> Second:
> IFE first step is that I get my tokens back on OMG network, second step after processing the exit is that I get back on the ethereum network? So... IFE is basically **revert transaction** + standard exit? Sorry, this might be very basic.

No, you don't get your tokens back on OMG network (child chain, right?) when you exit. Exiting means removing the tokens from the child chain and unlocking them on the root chain.

Not sure if I understand the question, but an IFE allows you to exit either the inputs or the outputs of a tx. If you start an IFE because you think a tx hasn't been included in a block, and piggyback an output, and later it's shown that the tx was actually put into a block; then that's almost exactly the same as a standard exit (but costs more gas because of the more complicated exit game).

Hmmm, maybe you're thinking about if the IFE is shown to be non-canonical because one of its inputs has been spent in another tx. In this case, the IFE tx is not so much **reverted** as **it never happened**. The spent input has been spent, so that can't be exited. However, if there is another input in the IFE tx that has not been spent in another tx, then it can be exited via piggybacking the IFE. 
This is not the same as reverting and standard exiting though. The output that that input is spending can never be standard exited, because even if the IFE tx is 'invalid' and will never be put into a block, the owner of that output has signed a tx to spend it, and that can be used to challenge a standard exit.

**Comment by InoMurko** [comment]
Before I test the second part...

> Observing the queues is pretty easy, but AFAIK whether and how we do this hasn't been set in stone yet.

Is this tracked somewhere? I presume it's a mainnet blocker, right?

**Comment by kevsul** [comment]
> Before I test the second part...
> 
> > Observing the queues is pretty easy, but AFAIK whether and how we do this hasn't been set in stone yet.
> 
> Is this tracked somewhere? I presume it's a mainnet blocker, right?

I wouldn't say it's a blocker, because it's an extra service that can be added on at any time

**Comment by InoMurko** [comment]
Two details I've noticed:
- the return value of `getNextExit(uint256,address)` is a composition, and it is not evident that you need to perform `exit_id = queue_next_exit_id &&& (1 <<< 160) - 1` @boolafish helped me on that and it might be useful to mention what the result means

- calling `processExits` and just looking at the transaction status being 0x1 is not enough. Meaning, it doesn't mean we've actually processed specified exits, but you need to observe if there were emitted events...
