### ISSUE TITLE
exit id for deposit is not unique 

### ISSUE THREAD

**Issue by pthomalla** [omisego/plasma-contracts#80]
## Issue Type 

```
[0] bug report
[ ] feature request
```

## Current Behavior

Create two deposit with this same data (`owner`, `token`, `amount`) generate the same deposit bytes.
Then `getStandardExitId` isn't unique, preventing exits 

## Expected Behavior

Change processDeposit to create unique `deposit` bytes.

- Command that caused error:  `function getStandardExitId(bytes32 _txhash, uint8 _oindex)` and  `function _processDeposit(bytes _depositTx, PlasmaCore.Transaction memory decodedTx)`

**Comment by pik694** [comment]
We thought about several solutions:
1. Instead of creating a deposit transaction with empty inputs, we could create a transaction
were the first input's `blknum` would be `nextDepositBlock` shifted left 128-bits. Such an approach would mean that in the protocol (or just a tinny part of it) we would be accepting spending inputs from the future. This may lead to problems in the future.
2. Instead of computing `exit_id` from `hash(txbytes)`, we could compute it from `hash(txbytes <> utxopos)`. Unfortunately this would not work, as we do not always have the `txoPos` (ex. in-flight transaction), therefore we would not be able to compute `exit_id` of IFE output.
3. The third solution, and the implemented one, is that we make a clear distinction between `exit_id` of deposit and any other transaction. If the transaction is an deposit the `exit_id` is computed from `hash(txbytes <> utxopos)`, which will always be unique, as blknums will be unique.  `Exit_id`s of other transactions remain being computed from `hash(tx_bytes)` only. The only problem is the fact that if we started an IFE from a deposit, we could not check whether someone tried to also SE the deposit, but this is not a problem, since we cannot start an IFE from the deposit - `sum of inputs < sum of outputs`.

**Comment by boolafish** [comment]
Thanks for the explanation of possible approaches! It is really helpful!

For the first approach, I 'd like to clarify:
> we would be accepting spending inputs from the future

Why is it "future"? Though it is `nextDepositBlock`, but that is the block where that certain deposit tx would be at. If the deposit succeeds, it will be "present" not "future". If it fails, it doesn't matter.

BTW, what are possible problems in the future that you've seen in using the first approach though?

I am asking this because the first approach looks more consistent within all exit-id creation, so I'd like to clarify the reason to prefer 3 over 1.

**Comment by boolafish** [comment]
Also, after the PR merged here, I think we need to update this doc as well: https://github.com/omisego/elixir-omg/blob/master/docs/mvp_morevp_interaction.md

**Comment by pdobacz** [comment]
>  think we need to update this doc as well: 

yep, we can do that in sync with upgrading `elixir-omg`'s `mix.exs` and it's version of contracts pointed to. But you're right - let's not forget that!

> reason to prefer 3 over 1.

(1.) introduces, in a way, a "notion" of a transaction which spends from the future (output position < input position == `nextDepositBlock << 128`), and is valid and included in the blockchain (one can prove this inclusion). In other words (1.) widens the scope of validity of transactions with a special case for deposits. (3.) has the benefit of acting more specifically to fix a specific issue: "if issue == exit id not unique, then let's fix the exit id", instead of making changes to a preceding step (tx encoding and hashing) and fixing exit ids "by coincidence" in a way.

That being said (1.) vs (3.) was indeed a bit of a judgmental call, both were close contenders.

**Comment by boolafish** [comment]
I re-look the contract code and just found out in (1) it is using `nextDepositBlock` instead of `blknum`.
I've been always misunderstood and thinking in the form of `blknum`: 
```
uint256 blknum = getDepositBlockNumber();
```

I think `nextDepositBlock` won't work because it only iterates from 1~999 (or 998?) and is reset whenever block submitted by the operator.
So it will crash again if deposit --> submit block (`nextDepositBlock` reset)--> deposit. (well...at the same time I don't really understand why `<<128`?)

On the other hand, if using `blknum` instead, (if I have the correct understanding) the output position would be the same as the input position. (Both input and output are using the same blknumber, and because there is only one tx in deposit block, `txindex` of output would be 0. And because only the first output has value, `oindex` of output is 0 as well). This still create a new "notion": where tx spends from itself. However, this might looks making-sense for deposit?

(BTW, this is more like technical discussion, I am fine with 3 and not meant to block the PR)

**Comment by pik694** [comment]
> I rethought about it and this will make the output "used" and would not be UTXO anymore.

This is why we could not just use `blknum` as it would mean that the transaction spends output it creates, therefore one could challenge the deposit UTXO as already used. This is why we thought about shifting the blknum left by 128 bits, which would mean that we are spending an UTXO from some block of a huge blknum (which we will never mine), but it is the future block.
