### ISSUE TITLE
Potential bug on IFE<>SE interaction

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#92]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Note
After a transaction is submitted, for unknown reason operator does not submit that tx into a block.
To prevent operator withholding, the output owner starts an IFE and piggybacked that.
All the sudden operator put that tx into block after the piggyback.
Now, input owner can piggyback IFE input, and simply create another IFE to make such IFE non-conical so that they can exit the input. 
And now we are left with a situation where in the plasma chain a officially "used tx" is allowed to exit.

**Comment by boolafish** [comment]
Have a gut feeling this is related to PivotTracker `timeout` story: https://www.pivotaltracker.com/story/show/162233131

Not really sure though.

**Comment by pdobacz** [comment]
I think this is different from `timeout` story you mention.

Also I can't see an attack there. I assume the scenario is like this:

1/ Alice has `utxo1` and spends it in `tx1` to Bob, `tx1` is submitted
2/ `tx1` is not included in a block
3/ Alice starts an IFE from `tx1` and piggybacks her funds, which is the input `utxo1` (Alice can also piggyback later in (6/) or (7/), doesn't matter)
4/ Since Bob didn't see `tx1` (it hasn't been included), we can assume that Bob piggybacks the output 1 from `tx1` (*)
5/ Operator includes `tx1` in a block after that
6/ the IFE of `tx1` has been canonical (the default every IFE starts off with) and still is after `tx1` is included
7/ Alice creates `tx2` spending `utxo1`, different from `tx1` in any way and starts an IFE out of that
8/ anyone submits `tx1` as a competitor to `tx2-IFE` and `tx2` as competitor to `tx1-IFE`, making both non-canonical.
9/ anyone submits a challenge to Alice's input piggybacks in `tx1` and `tx2` IFEs, rendering both exits impossible forever
10/ the only thing that can happen now is that when someone sees the inclusion of `tx1` (e.g. Bob), they can submit a `prove_canonical` message, rendering `tx1-IFE` canonical again, making Bob's output exitable. This is fine, it would effectively make Bob "accept" the original payment from Alice

So as the game played out
1/ Operator doesn't steal anything
2/ Alice doesn't steal anything and gets punished with losing her bonds *and* potentially losing her payment to Bob irreversibly
3/ Bob can still provably accept the payment, if he sees the inclusion and plays along

* If Bob didn't piggyback the output 1, it would mean that he claims to have seen `tx1` included and forfeits the IFE opportunity. Finally, this has no impact on how the scenario plays out

**Comment by boolafish** [comment]
ah, apparently I forgot we can challenge piggybacked IFE input double spending. So yeah, Alice cannot steal anything and would just be punished.

However, I don't understand how `10/` works. (do we have that `prove_canonical` mechanism and to open tx1-IFE again now?) From the code, I guess we cannot re-start IFE, can we? 

My guess is that it would be block by the following line:
```
require(inFlightExit.exitStartTimestamp == 0);
```

Also, What I see from the code is the output owner cannot SE because it is piggybacked already. 
And, logically speaking, I think SE instead of IFE should be the right action to take since the block is valid.

**Comment by pdobacz** [comment]
> However, I don't understand how `10/` works. (do we have that `prove_canonical` mechanism and to open tx1-IFE again now?)

yes, sorry, I used the wrong name of function [respondToNonCanonicalChallenge](https://github.com/omisego/plasma-contracts/blob/master/contracts/RootChain.sol#L683) is the one

This doesn't require reopening (which is illegal, as you have seen).

> Logically speaking, I think SE instead of IFE

This boils down to the (*) I left at the bottom of my comment (sorry it renderd as a bullet, now fixed that).

So if Bob hasn't seen `tx1` he would piggyback the IFE output, if he had seen `tx1` **safely** included, he'd SE (or spend on). Bob's behavior depends on when he comes online and decides - after the "late" inclusion of `tx1` or before.

Since, per assumption, Alice hasn't seen `tx1` included when she looked for it, she'd IFE+piggyback input.

Perspective of Alice and Bob is different, and is the main drive behind their actions.

**Comment by boolafish** [comment]
oh! okay, apparently I missed `respondToNonCanonicalChallenge` as well ><
Yeah, it make sense to keep on the IFE to exit output in this case. 
Thanks for the explanation!

Close this issue as it's not an issue.
